language: node_js
node_js:
  - '8'
sudo: false
install:
  - npm i
  - npm i -g codecov
script:
  - npm run coverage
  - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - codecov
  - npm run test
cache:
  directories:
    - node_modules