language: node_js
node_js:
  - '8'
sudo: false
install:
  - npm i
  - npm i -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - npm run test
cache:
  directories:
    - node_modules